import { createClient } from '@supabase/supabase-js'
import dotenv from 'dotenv'

// .env.localファイルを読み込み
dotenv.config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

async function addMoreTestData() {
  try {
    console.log('追加テストデータを検索中...')
    
    // テストユーザーを検索
    const { data: users, error } = await supabase.auth.admin.listUsers()

    if (error) {
      console.error('ユーザー検索エラー:', error)
      return
    }

    const testUser = users.users.find(user => user.email === 'test@cooooster.com')

    if (testUser) {
      console.log('✅ テストユーザーが見つかりました！')
      console.log('ユーザーID:', testUser.id)
      console.log('')
      console.log('以下のSQLをSupabaseダッシュボードで実行してください:')
      console.log('')
      console.log(`-- 追加テスト用コレクションデータ`)
      console.log(`INSERT INTO public.collected_areas (user_id, area_name, created_at, updated_at) VALUES`)
      
      // 北海道の海岸線エリア
      console.log(`-- 北海道の海岸線エリア`)
      console.log(`('${testUser.id}', '札幌市', now(), now()),`)
      console.log(`('${testUser.id}', '函館市', now(), now()),`)
      console.log(`('${testUser.id}', '小樽市', now(), now()),`)
      console.log(`('${testUser.id}', '室蘭市', now(), now()),`)
      console.log(`('${testUser.id}', '苫小牧市', now(), now()),`)
      console.log(`('${testUser.id}', '江別市', now(), now()),`)
      console.log(`('${testUser.id}', '千歳市', now(), now()),`)
      console.log(`('${testUser.id}', '石狩市', now(), now()),`)
      console.log(`('${testUser.id}', '北広島市', now(), now()),`)
      console.log(`('${testUser.id}', '恵庭市', now(), now()),`)
      
      // 東北地方の海岸線エリア
      console.log(`-- 東北地方の海岸線エリア`)
      console.log(`('${testUser.id}', '青森市', now(), now()),`)
      console.log(`('${testUser.id}', '弘前市', now(), now()),`)
      console.log(`('${testUser.id}', '八戸市', now(), now()),`)
      console.log(`('${testUser.id}', '秋田市', now(), now()),`)
      console.log(`('${testUser.id}', '能代市', now(), now()),`)
      console.log(`('${testUser.id}', '仙台市', now(), now()),`)
      console.log(`('${testUser.id}', '石巻市', now(), now()),`)
      console.log(`('${testUser.id}', '塩竈市', now(), now()),`)
      console.log(`('${testUser.id}', '気仙沼市', now(), now()),`)
      console.log(`('${testUser.id}', '山形市', now(), now()),`)
      console.log(`('${testUser.id}', '米沢市', now(), now()),`)
      console.log(`('${testUser.id}', '鶴岡市', now(), now()),`)
      console.log(`('${testUser.id}', '酒田市', now(), now()),`)
      console.log(`('${testUser.id}', '福島市', now(), now()),`)
      console.log(`('${testUser.id}', '会津若松市', now(), now()),`)
      console.log(`('${testUser.id}', '郡山市', now(), now()),`)
      console.log(`('${testUser.id}', 'いわき市', now(), now()),`)
      console.log(`('${testUser.id}', '白河市', now(), now()),`)
      console.log(`('${testUser.id}', '須賀川市', now(), now()),`)
      console.log(`('${testUser.id}', '相馬市', now(), now()),`)
      
      // 静岡県の海岸線エリア
      console.log(`-- 静岡県の海岸線エリア`)
      console.log(`('${testUser.id}', '静岡市', now(), now()),`)
      console.log(`('${testUser.id}', '浜松市', now(), now()),`)
      console.log(`('${testUser.id}', '沼津市', now(), now()),`)
      console.log(`('${testUser.id}', '熱海市', now(), now()),`)
      console.log(`('${testUser.id}', '伊東市', now(), now()),`)
      console.log(`('${testUser.id}', '下田市', now(), now()),`)
      console.log(`('${testUser.id}', '富士市', now(), now()),`)
      console.log(`('${testUser.id}', '富士宮市', now(), now()),`)
      console.log(`('${testUser.id}', '御前崎市', now(), now()),`)
      console.log(`('${testUser.id}', '菊川市', now(), now()),`)
      
      // 愛知県の海岸線エリア
      console.log(`-- 愛知県の海岸線エリア`)
      console.log(`('${testUser.id}', '名古屋市', now(), now()),`)
      console.log(`('${testUser.id}', '豊橋市', now(), now()),`)
      console.log(`('${testUser.id}', '岡崎市', now(), now()),`)
      console.log(`('${testUser.id}', '一宮市', now(), now()),`)
      console.log(`('${testUser.id}', '春日井市', now(), now()),`)
      console.log(`('${testUser.id}', '津島市', now(), now()),`)
      console.log(`('${testUser.id}', '碧南市', now(), now()),`)
      console.log(`('${testUser.id}', '刈谷市', now(), now()),`)
      console.log(`('${testUser.id}', '豊田市', now(), now()),`)
      console.log(`('${testUser.id}', '安城市', now(), now()),`)
      
      // 三重県の海岸線エリア
      console.log(`-- 三重県の海岸線エリア`)
      console.log(`('${testUser.id}', '津市', now(), now()),`)
      console.log(`('${testUser.id}', '四日市市', now(), now()),`)
      console.log(`('${testUser.id}', '松阪市', now(), now()),`)
      console.log(`('${testUser.id}', '桑名市', now(), now()),`)
      console.log(`('${testUser.id}', '鈴鹿市', now(), now()),`)
      console.log(`('${testUser.id}', '名張市', now(), now()),`)
      console.log(`('${testUser.id}', '尾鷲市', now(), now()),`)
      console.log(`('${testUser.id}', '熊野市', now(), now()),`)
      console.log(`('${testUser.id}', '伊勢市', now(), now()),`)
      console.log(`('${testUser.id}', '鳥羽市', now(), now()),`)
      
      // 和歌山県の海岸線エリア
      console.log(`-- 和歌山県の海岸線エリア`)
      console.log(`('${testUser.id}', '和歌山市', now(), now()),`)
      console.log(`('${testUser.id}', '海南市', now(), now()),`)
      console.log(`('${testUser.id}', '御坊市', now(), now()),`)
      console.log(`('${testUser.id}', '田辺市', now(), now()),`)
      console.log(`('${testUser.id}', '新宮市', now(), now()),`)
      console.log(`('${testUser.id}', '紀の川市', now(), now()),`)
      console.log(`('${testUser.id}', '岩出市', now(), now()),`)
      console.log(`('${testUser.id}', '橋本市', now(), now()),`)
      console.log(`('${testUser.id}', '有田市', now(), now()),`)
      console.log(`('${testUser.id}', '串本町', now(), now()),`)
      
      // 大阪府の海岸線エリア
      console.log(`-- 大阪府の海岸線エリア`)
      console.log(`('${testUser.id}', '大阪市', now(), now()),`)
      console.log(`('${testUser.id}', '堺市', now(), now()),`)
      console.log(`('${testUser.id}', '岸和田市', now(), now()),`)
      console.log(`('${testUser.id}', '泉大津市', now(), now()),`)
      console.log(`('${testUser.id}', '泉佐野市', now(), now()),`)
      console.log(`('${testUser.id}', '高石市', now(), now()),`)
      console.log(`('${testUser.id}', '泉南市', now(), now()),`)
      console.log(`('${testUser.id}', '阪南市', now(), now()),`)
      console.log(`('${testUser.id}', '貝塚市', now(), now()),`)
      console.log(`('${testUser.id}', '泉北郡忠岡町', now(), now()),`)
      
      // 兵庫県の海岸線エリア
      console.log(`-- 兵庫県の海岸線エリア`)
      console.log(`('${testUser.id}', '神戸市', now(), now()),`)
      console.log(`('${testUser.id}', '姫路市', now(), now()),`)
      console.log(`('${testUser.id}', '尼崎市', now(), now()),`)
      console.log(`('${testUser.id}', '明石市', now(), now()),`)
      console.log(`('${testUser.id}', '西宮市', now(), now()),`)
      console.log(`('${testUser.id}', '芦屋市', now(), now()),`)
      console.log(`('${testUser.id}', '伊丹市', now(), now()),`)
      console.log(`('${testUser.id}', '宝塚市', now(), now()),`)
      console.log(`('${testUser.id}', '川西市', now(), now()),`)
      console.log(`('${testUser.id}', '三田市', now(), now()),`)
      
      // 岡山県の海岸線エリア
      console.log(`-- 岡山県の海岸線エリア`)
      console.log(`('${testUser.id}', '岡山市', now(), now()),`)
      console.log(`('${testUser.id}', '倉敷市', now(), now()),`)
      console.log(`('${testUser.id}', '津山市', now(), now()),`)
      console.log(`('${testUser.id}', '玉野市', now(), now()),`)
      console.log(`('${testUser.id}', '笠岡市', now(), now()),`)
      console.log(`('${testUser.id}', '井原市', now(), now()),`)
      console.log(`('${testUser.id}', '総社市', now(), now()),`)
      console.log(`('${testUser.id}', '高梁市', now(), now()),`)
      console.log(`('${testUser.id}', '新見市', now(), now()),`)
      console.log(`('${testUser.id}', '備前市', now(), now()),`)
      
      // 広島県の海岸線エリア
      console.log(`-- 広島県の海岸線エリア`)
      console.log(`('${testUser.id}', '広島市', now(), now()),`)
      console.log(`('${testUser.id}', '呉市', now(), now()),`)
      console.log(`('${testUser.id}', '竹原市', now(), now()),`)
      console.log(`('${testUser.id}', '三原市', now(), now()),`)
      console.log(`('${testUser.id}', '尾道市', now(), now()),`)
      console.log(`('${testUser.id}', '福山市', now(), now()),`)
      console.log(`('${testUser.id}', '府中市', now(), now()),`)
      console.log(`('${testUser.id}', '三次市', now(), now()),`)
      console.log(`('${testUser.id}', '庄原市', now(), now()),`)
      console.log(`('${testUser.id}', '大竹市', now(), now()),`)
      
      // 山口県の海岸線エリア
      console.log(`-- 山口県の海岸線エリア`)
      console.log(`('${testUser.id}', '下関市', now(), now()),`)
      console.log(`('${testUser.id}', '宇部市', now(), now()),`)
      console.log(`('${testUser.id}', '山口市', now(), now()),`)
      console.log(`('${testUser.id}', '萩市', now(), now()),`)
      console.log(`('${testUser.id}', '防府市', now(), now()),`)
      console.log(`('${testUser.id}', '下松市', now(), now()),`)
      console.log(`('${testUser.id}', '岩国市', now(), now()),`)
      console.log(`('${testUser.id}', '光市', now(), now()),`)
      console.log(`('${testUser.id}', '長門市', now(), now()),`)
      console.log(`('${testUser.id}', '柳井市', now(), now()),`)
      
      // 四国地方の海岸線エリア
      console.log(`-- 四国地方の海岸線エリア`)
      console.log(`('${testUser.id}', '徳島市', now(), now()),`)
      console.log(`('${testUser.id}', '鳴門市', now(), now()),`)
      console.log(`('${testUser.id}', '小松島市', now(), now()),`)
      console.log(`('${testUser.id}', '阿南市', now(), now()),`)
      console.log(`('${testUser.id}', '松山市', now(), now()),`)
      console.log(`('${testUser.id}', '今治市', now(), now()),`)
      console.log(`('${testUser.id}', '宇和島市', now(), now()),`)
      console.log(`('${testUser.id}', '八幡浜市', now(), now()),`)
      console.log(`('${testUser.id}', '新居浜市', now(), now()),`)
      console.log(`('${testUser.id}', '西条市', now(), now()),`)
      console.log(`('${testUser.id}', '高松市', now(), now()),`)
      console.log(`('${testUser.id}', '丸亀市', now(), now()),`)
      console.log(`('${testUser.id}', '坂出市', now(), now()),`)
      console.log(`('${testUser.id}', '善通寺市', now(), now()),`)
      console.log(`('${testUser.id}', '観音寺市', now(), now()),`)
      console.log(`('${testUser.id}', 'さぬき市', now(), now()),`)
      console.log(`('${testUser.id}', '東かがわ市', now(), now()),`)
      console.log(`('${testUser.id}', '三豊市', now(), now()),`)
      console.log(`('${testUser.id}', '高知市', now(), now()),`)
      console.log(`('${testUser.id}', '室戸市', now(), now()),`)
      
      // 九州地方の海岸線エリア
      console.log(`-- 九州地方の海岸線エリア`)
      console.log(`('${testUser.id}', '北九州市', now(), now()),`)
      console.log(`('${testUser.id}', '福岡市', now(), now()),`)
      console.log(`('${testUser.id}', '大牟田市', now(), now()),`)
      console.log(`('${testUser.id}', '久留米市', now(), now()),`)
      console.log(`('${testUser.id}', '直方市', now(), now()),`)
      console.log(`('${testUser.id}', '飯塚市', now(), now()),`)
      console.log(`('${testUser.id}', '田川市', now(), now()),`)
      console.log(`('${testUser.id}', '柳川市', now(), now()),`)
      console.log(`('${testUser.id}', '八女市', now(), now()),`)
      console.log(`('${testUser.id}', '筑後市', now(), now()),`)
      console.log(`('${testUser.id}', '佐賀市', now(), now()),`)
      console.log(`('${testUser.id}', '唐津市', now(), now()),`)
      console.log(`('${testUser.id}', '鳥栖市', now(), now()),`)
      console.log(`('${testUser.id}', '多久市', now(), now()),`)
      console.log(`('${testUser.id}', '伊万里市', now(), now()),`)
      console.log(`('${testUser.id}', '武雄市', now(), now()),`)
      console.log(`('${testUser.id}', '鹿島市', now(), now()),`)
      console.log(`('${testUser.id}', '小城市', now(), now()),`)
      console.log(`('${testUser.id}', '嬉野市', now(), now()),`)
      console.log(`('${testUser.id}', '神埼市', now(), now()),`)
      console.log(`('${testUser.id}', '長崎市', now(), now()),`)
      console.log(`('${testUser.id}', '佐世保市', now(), now()),`)
      console.log(`('${testUser.id}', '島原市', now(), now()),`)
      console.log(`('${testUser.id}', '諫早市', now(), now()),`)
      console.log(`('${testUser.id}', '大村市', now(), now()),`)
      console.log(`('${testUser.id}', '平戸市', now(), now()),`)
      console.log(`('${testUser.id}', '松浦市', now(), now()),`)
      console.log(`('${testUser.id}', '対馬市', now(), now()),`)
      console.log(`('${testUser.id}', '五島市', now(), now()),`)
      console.log(`('${testUser.id}', '西海市', now(), now()),`)
      console.log(`('${testUser.id}', '雲仙市', now(), now()),`)
      console.log(`('${testUser.id}', '南島原市', now(), now()),`)
      console.log(`('${testUser.id}', '熊本市', now(), now()),`)
      console.log(`('${testUser.id}', '八代市', now(), now()),`)
      console.log(`('${testUser.id}', '人吉市', now(), now()),`)
      console.log(`('${testUser.id}', '荒尾市', now(), now()),`)
      console.log(`('${testUser.id}', '水俣市', now(), now()),`)
      console.log(`('${testUser.id}', '玉名市', now(), now()),`)
      console.log(`('${testUser.id}', '山鹿市', now(), now()),`)
      console.log(`('${testUser.id}', '菊池市', now(), now()),`)
      console.log(`('${testUser.id}', '宇土市', now(), now()),`)
      console.log(`('${testUser.id}', '上天草市', now(), now()),`)
      console.log(`('${testUser.id}', '宇城市', now(), now()),`)
      console.log(`('${testUser.id}', '阿蘇市', now(), now()),`)
      console.log(`('${testUser.id}', '天草市', now(), now()),`)
      console.log(`('${testUser.id}', '合志市', now(), now()),`)
      console.log(`('${testUser.id}', '大分市', now(), now()),`)
      console.log(`('${testUser.id}', '別府市', now(), now()),`)
      console.log(`('${testUser.id}', '中津市', now(), now()),`)
      console.log(`('${testUser.id}', '日田市', now(), now()),`)
      console.log(`('${testUser.id}', '佐伯市', now(), now()),`)
      console.log(`('${testUser.id}', '臼杵市', now(), now()),`)
      console.log(`('${testUser.id}', '津久見市', now(), now()),`)
      console.log(`('${testUser.id}', '竹田市', now(), now()),`)
      console.log(`('${testUser.id}', '豊後高田市', now(), now()),`)
      console.log(`('${testUser.id}', '杵築市', now(), now()),`)
      console.log(`('${testUser.id}', '宇佐市', now(), now()),`)
      console.log(`('${testUser.id}', '豊後大野市', now(), now()),`)
      console.log(`('${testUser.id}', '由布市', now(), now()),`)
      console.log(`('${testUser.id}', '国東市', now(), now()),`)
      console.log(`('${testUser.id}', '宮崎市', now(), now()),`)
      console.log(`('${testUser.id}', '都城市', now(), now()),`)
      console.log(`('${testUser.id}', '延岡市', now(), now()),`)
      console.log(`('${testUser.id}', '日南市', now(), now()),`)
      console.log(`('${testUser.id}', '小林市', now(), now()),`)
      console.log(`('${testUser.id}', '日向市', now(), now()),`)
      console.log(`('${testUser.id}', '串間市', now(), now()),`)
      console.log(`('${testUser.id}', '西都市', now(), now()),`)
      console.log(`('${testUser.id}', 'えびの市', now(), now()),`)
      console.log(`('${testUser.id}', '鹿児島市', now(), now()),`)
      console.log(`('${testUser.id}', '鹿屋市', now(), now()),`)
      console.log(`('${testUser.id}', '枕崎市', now(), now()),`)
      console.log(`('${testUser.id}', '阿久根市', now(), now()),`)
      console.log(`('${testUser.id}', '出水市', now(), now()),`)
      console.log(`('${testUser.id}', '指宿市', now(), now()),`)
      console.log(`('${testUser.id}', '西之表市', now(), now()),`)
      console.log(`('${testUser.id}', '垂水市', now(), now()),`)
      console.log(`('${testUser.id}', '薩摩川内市', now(), now()),`)
      console.log(`('${testUser.id}', '日置市', now(), now()),`)
      console.log(`('${testUser.id}', '曽於市', now(), now()),`)
      console.log(`('${testUser.id}', '霧島市', now(), now()),`)
      console.log(`('${testUser.id}', 'いちき串木野市', now(), now()),`)
      console.log(`('${testUser.id}', '南さつま市', now(), now()),`)
      console.log(`('${testUser.id}', '志布志市', now(), now()),`)
      console.log(`('${testUser.id}', '奄美市', now(), now()),`)
      console.log(`('${testUser.id}', '南九州市', now(), now()),`)
      console.log(`('${testUser.id}', '伊佐市', now(), now()),`)
      console.log(`('${testUser.id}', '姶良市', now(), now()),`)
      console.log(`('${testUser.id}', '那覇市', now(), now()),`)
      console.log(`('${testUser.id}', '宜野湾市', now(), now()),`)
      console.log(`('${testUser.id}', '石垣市', now(), now()),`)
      console.log(`('${testUser.id}', '浦添市', now(), now()),`)
      console.log(`('${testUser.id}', '名護市', now(), now()),`)
      console.log(`('${testUser.id}', '糸満市', now(), now()),`)
      console.log(`('${testUser.id}', '沖縄市', now(), now()),`)
      console.log(`('${testUser.id}', '豊見城市', now(), now()),`)
      console.log(`('${testUser.id}', 'うるま市', now(), now()),`)
      console.log(`('${testUser.id}', '宮古島市', now(), now()),`)
      console.log(`('${testUser.id}', '南城市', now(), now());`)
      
      console.log('')
      console.log('これで合計400以上の海岸線エリアがコレクションされます！')
      console.log('')
      console.log('ログイン情報:')
      console.log('メールアドレス: test@cooooster.com')
      console.log('パスワード: password123')
    } else {
      console.log('❌ テストユーザーが見つかりませんでした')
    }

  } catch (error) {
    console.error('エラーが発生しました:', error)
  }
}

addMoreTestData() 